spring:
  application:
    name: user-service

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  configs:
    default:
      registerHealthIndicator: true

  retry:
    instances:
      orderService:
        max-attempts: 3
        wait-duration: 2s

logging:
  level:
    io.github.resilience4j: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka